### PR TITLE
adding lab notebooks paper

### PR DESCRIPTION
**Pull request by akashdhruv**

### CODE REVIEW

**Comment by akashdhruv** [comment]
The changes are in red

**Comment by labarba** [comment]
hi @akashdhruv — looks like you forgot to include the `.bib` file

**Comment by akashdhruv** [comment]
We have added bibliography as \bibitem directly in Paper.tex

**Comment by labarba** [comment]
I'm getting multiple errors in VS Code with the LaTeX Workshop extension. Let me try in TexShop and see what happens.

**Comment by labarba** [comment]
It choked here:

```
./minted.sty:1015: Undefined control sequence.
l.1015 \FVExtrapdfstringdefDisableCommands
                                          {%
? 
./minted.sty:1048: Undefined control sequence.
l.1048 \FVExtrapdfstringdefDisableCommands
                                          {%
? 
```

…but ignoring these with Enter generated a PDF. Checking it now.

**Comment by labarba** [comment]
OK, that looks good. Please clean up the source file removing comments and the red highlighting and submit a new PR. (Commented texts in the source are possible sources of human error in production.)

**Comment by akashdhruv** [comment]
Ok I will do that shortly. Please make sure that despite the error produced by minted.sty, the code blocks in figures are still rendered with proper syntax.

**Comment by labarba** [comment]
BTW, I noticed that you have a Zenodo deposit for `Jobrunner`—do you want to cite that more permanent object, instead of the repo (or in addition to)? (Did you submit it to JOSS, by any chance? I noticed the Statement of need. If it is under review there, you can cite that.)

**Comment by akashdhruv** [comment]
The JOSS paper did not pass the pre-review stage due to the length of the code. I will create a Zenodo DOI for the latest version and add it this evening

**Comment by akashdhruv** [comment]
Continued to #2

**Pull request merged**
